Repository gacela-project/router, pull requests merged in 2023-04, with the labels that each got.

#1 Create RoutingConfigurator
  src/Router/Route.php
  src/Router/RoutingConfigurator.php
  tests/Unit/Router/RouteTest.php
Labels: enhancement

#2 Refactor extract class RouteParams
  example/example.php
  src/Router/Request.php
  src/Router/Route.php
  src/Router/RouteParams.php
  tests/Unit/Router/RouteTest.php
Labels: refactoring

#3 UnsupportedHttpMethodException if HTTP verb is invalid
  src/Router/RoutingConfigurator.php
  src/Router/UnsupportedHttpMethodException.php
  tests/Unit/Router/RouteTest.php
Labels: enhancement

#4 Support all routes with "any"
  src/Router/Request.php
  src/Router/RoutingConfigurator.php
  tests/Unit/Router/RouteTest.php
Labels: enhancement

#6 Allow redirect routes
  README.md
  composer.json
  example/example.php
  src/Router/Redirect.php
  src/Router/RedirectController.php
  src/Router/Route.php
  src/Router/Routing.php
  src/Router/RoutingConfigurator.php
  tests/Unit/Router/Fake/header.php
  tests/Unit/Router/Fixtures/HeadersTearDown.php
  tests/Unit/Router/RoutingRedirectTest.php
  tests/Unit/Router/RoutingTest.php
Labels: enhancement

#8 Inject Request in Controller's constructor
  README.md
  composer.json
  example/example.php
  src/Router/MappingInterfaces.php
  tests/Unit/Router/Fixtures/FakeControllerWithRequest.php
  tests/Unit/Router/RouterRedirectTest.php
  tests/Unit/Router/RouterTest.php
Labels: documentation, enhancement

#11 Trigger NotFound404Controller if no Route was found
  phpunit.xml
  src/Router/Controllers/NotFound404Controller.php
  src/Router/Router.php
  tests/Feature/HeaderTestCase.php
  tests/Feature/Router/ErrorHandlingTest.php
  tests/Feature/Router/Fake/Name.php
  tests/Feature/Router/Fake/NameInterface.php
  tests/Feature/Router/Fixtures/FakeController.php
  tests/Feature/Router/Fixtures/FakeControllerWithDependencies.php
  tests/Feature/Router/Fixtures/FakeControllerWithRequest.php
  tests/Feature/Router/RouterInjectionTest.php
  tests/Feature/Router/RouterMatchTest.php
  tests/Feature/Router/RouterParamTest.php
  tests/Feature/Router/RouterRedirectTest.php
  tests/Feature/header.php
  tests/Unit/Router/Fixtures/HeadersTearDown.php
Labels: enhancement

#13 Error handler
  README.md
  src/Router/Bindings.php
  src/Router/Entities/Route.php
  src/Router/Handlers.php
  src/Router/Router.php
  src/Router/Routes.php
  tests/Feature/Router/ErrorHandlingTest.php
  tests/Feature/Router/Fixtures/FakeControllerWithUnhandledException.php
  tests/Feature/Router/Fixtures/UnhandledException.php
  tests/Feature/Router/RouterBindingTest.php
  tests/Feature/Router/RouterMatchTest.php
  tests/Feature/Router/RouterParamTest.php
  tests/Feature/header.php
Labels: enhancement

#16 Support class handlers
  src/Router/Handlers.php
  src/Router/Router.php
  tests/Feature/Router/ErrorHandlingTest.php
Labels: enhancement

#17 Add named constructor for UnsupportedHttpMethodException
  src/Router/Exceptions/UnsupportedHttpMethodException.php
  src/Router/Router.php
  src/Router/Routes.php
Labels: refactoring

#18 Improve readme example
  README.md
Labels: documentation

#19 Create JsonResponse
  src/Router/Entities/JsonResponse.php
  src/Router/Entities/Response.php
  tests/Feature/HeaderTestCase.php
  tests/Feature/Router/RouterResponseTest.php
  tests/Feature/header.php
Labels: enhancement

#20 Allow headers in Response
  example/example.php
  src/Router/Entities/JsonResponse.php
  src/Router/Entities/Response.php
  tests/Feature/Router/RouterResponseTest.php
Labels: enhancement

#24 Upgrade container:0.3
  composer.json
  psalm.xml
  src/Router/Entities/Route.php
  src/Router/Router.php
Labels: enhancement

#26 Allow adding routes in different steps
  example/example.php
  src/Router/Router.php
  tests/Feature/Router/RouterRunTest.php
Labels: enhancement
